name: Tests

on: [ push, pull_request ]

jobs:
  jdk:
    name: JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [ '17' ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - run: ./gradlew jvmTest koverMergedXmlReport
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/build/kover/result.xml
          token: ${{ secrets.GITHUB_TOKEN }}